/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csv_parser;

import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eug
 */
public class CategorizerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CategorizerJFrame
     */
    public CategorizerJFrame() {
        initComponents();
    }
    
    public void setMissingCategoriesTextArea(String s) {
        missingCategoriesTextArea.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        categoryComboBox = new javax.swing.JComboBox<>();
        applyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        missingCategoriesTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        categorizeTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Category>", "Cheesy Bread", "Dog", "Pub", "Salad", "Square", "Side", "Other/Ignore" }));
        categoryComboBox.setToolTipText("");
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("The following items are missing categories. Please categorize below.");

        jLabel2.setText("Separate values with commas (copy and paste from above).");

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        missingCategoriesTextArea.setColumns(20);
        missingCategoriesTextArea.setRows(5);
        jScrollPane2.setViewportView(missingCategoriesTextArea);

        categorizeTextArea.setColumns(20);
        categorizeTextArea.setRows(5);
        jScrollPane3.setViewportView(categorizeTextArea);

        jLabel3.setText("Category:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneButton)
                    .addComponent(applyButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        
        int selectedInd = categoryComboBox.getSelectedIndex();
        if (selectedInd == 0) {
            JOptionPane.showMessageDialog(null, "Please select a category", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        String category = categoryComboBox.getItemAt(selectedInd);
        String[] items = categorizeTextArea.getText().split(",");
        
        try { 
            FileWriter pw = new FileWriter("category.csv",true);
            
            for(String item : items) {
                item = item.trim();
                pw.append(item + "," + category + "\n");
                
                String missingCat = missingCategoriesTextArea.getText();
                int startDel = missingCat.indexOf(item);
                               
                missingCategoriesTextArea.setText(missingCat.substring(0, startDel) + 
                        "*CATEGORIZED*" +
                        missingCat.substring(startDel + item.length()));
            }
            
            pw.flush();
            pw.close();
            
            categorizeTextArea.setText(null);
            JOptionPane.showMessageDialog(null, "Sucessfully categorized items.", "Success", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "category.csv doesn't exist.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
        categoryComboBox.addItem("Cheesy Bread");
        categoryComboBox.addItem("Dog");
        categoryComboBox.addItem("Pub");
        categoryComboBox.addItem("Salad");
        categoryComboBox.addItem("Square");
        categoryComboBox.addItem("Side");
        categoryComboBox.addItem("Other/Ignore");
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        setVisible(false);
        JOptionPane.showMessageDialog(null, "Sucessful conversion.", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_doneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JTextArea categorizeTextArea;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea missingCategoriesTextArea;
    // End of variables declaration//GEN-END:variables
}
